<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Submit</name>
   <tag></tag>
   <elementGuidId>ebedb01b-3cd2-4881-b498-027992971d89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='submit_contact_us']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit_contact_us</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1a2bb83-0a8f-4825-a7df-a4e1cb4cc806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit_button</value>
      <webElementGuid>4f3db336-d851-4f2d-a0a6-7a80a516a88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit_contact_us</value>
      <webElementGuid>2973da8c-9395-4302-bca5-f9106aca2b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>2d901f56-1805-4025-b5a2-fd41454028ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit_contact_us&quot;)</value>
      <webElementGuid>fc6dffee-2760-4552-bd30-242c83fee72d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='submit_contact_us']</value>
      <webElementGuid>c92b8b0d-d23f-40c9-806a-e8d9d680940c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pop-up-contact-us']/div/div/div/div[2]/div[9]/div</value>
      <webElementGuid>9e8b2ff8-fccb-4dcf-9e65-ddb6c396d296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/following::div[2]</value>
      <webElementGuid>2f85a9f9-f05a-4f8c-87de-11ec326898d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::div[13]</value>
      <webElementGuid>06366c24-9b22-491b-bf14-b4111560fd1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here!'])[1]/preceding::div[1]</value>
      <webElementGuid>8ab1c0e5-b3b1-4c26-bf6f-6f977c715525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>f9dbc149-c96f-4733-b558-ea6b9f2af122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div</value>
      <webElementGuid>9cd3d9b9-68c0-409b-8078-58eed70a2578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'submit_contact_us' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>0e8c8b88-066e-4bef-a3cb-5dc24a01ceb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
