<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_div</name>
   <tag></tag>
   <elementGuidId>233c11e0-3207-45cf-9f5a-c4480876858f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='chilipiper-frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chilipiper-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>41330729-ba9e-470d-909c-ab9ef963c6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chilipiper-frame</value>
      <webElementGuid>23364608-2b47-49d1-92a3-7e64c29455a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chilipiper-frame</value>
      <webElementGuid>801f022c-7f56-433a-a8de-c55d71aed7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://katalon.chilipiper.com/book/catch-all1/?id=003BV00000295bcYAA&amp;routeId=642fd2c2bea0c164842d80d6&amp;marketing=true&amp;title=&amp;titleStyle=&amp;fromSnippet=true</value>
      <webElementGuid>eb78d01a-967c-4985-9d10-b347737ee898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bb80014d-c63d-4256-baf1-d6b6a7c1b14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-description</name>
      <type>Main</type>
      <value>Page with slots</value>
      <webElementGuid>9984fe05-e7da-4fc9-b295-5ffad501772e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                &lt;/div>
            </value>
      <webElementGuid>4501b323-bc19-4c3b-95a6-1d5d0b35a83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chilipiper-frame&quot;)</value>
      <webElementGuid>d7237661-7c8f-4b87-b5b0-67d58b7bc81d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='chilipiper-frame']</value>
      <webElementGuid>2e486da9-7d89-44c3-9e5f-e2f86c503137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'chilipiper-frame', '&quot;', ')')])[1]/following::iframe[4]</value>
      <webElementGuid>355594b9-4515-46ff-8dbd-a74d07def5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here!'])[1]/following::iframe[4]</value>
      <webElementGuid>107f0a7d-d7cf-444c-bd31-76b75f892eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;/div>']/parent::*</value>
      <webElementGuid>95c66377-b04e-4870-bb91-9a1fadae7a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/iframe</value>
      <webElementGuid>fdc84c06-bfc0-4872-b6f2-c4752fd6bb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'chilipiper-frame' and @src = 'https://katalon.chilipiper.com/book/catch-all1/?id=003BV00000295bcYAA&amp;routeId=642fd2c2bea0c164842d80d6&amp;marketing=true&amp;title=&amp;titleStyle=&amp;fromSnippet=true' and (text() = '
                &lt;/div>
            ' or . = '
                &lt;/div>
            ')]</value>
      <webElementGuid>ab29bc93-7d08-436f-8954-3c5c9f94a3a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
