<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Us_email_contact_us</name>
   <tag></tag>
   <elementGuidId>d1ef954b-bab2-42fc-971e-ebff7d5c6724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_contact_us']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email_contact_us</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92d3cf60-948d-4951-b4b1-d6d11608e505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b9c9ea59-97d2-49de-9264-25fe0a83deab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_contact_us</value>
      <webElementGuid>e1b5ad7c-677c-4eb8-b397-36f41efde65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Business email*</value>
      <webElementGuid>276fd747-85f4-41f9-a0bd-085c23f037d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_contact_us&quot;)</value>
      <webElementGuid>294f08ee-b6fd-4070-ae82-2b381ad09460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_contact_us']</value>
      <webElementGuid>621e5c9e-1ee5-42b7-9f2f-fe0d22ef923b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pop-up-contact-us']/div/div/div/div[2]/div[4]/input</value>
      <webElementGuid>ebc8680e-b758-4f06-9d78-1d12ae314fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>c69fbc2f-c50f-4727-bee1-1e275a586f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'email_contact_us' and @placeholder = 'Business email*']</value>
      <webElementGuid>c108db38-cacf-497d-8e9d-613710541fbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
