<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Annual</name>
   <tag></tag>
   <elementGuidId>da85c90d-5e20-4a35-ada1-af1432b2fef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[2]/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn_change_select_type.btn_change_select_type_yearly</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1573465f-5342-4b1f-99e4-56f0be871164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_change_select_type btn_change_select_type_yearly</value>
      <webElementGuid>79dfce99-a4ea-4e1a-9564-aa19fcaa9d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type-plan</name>
      <type>Main</type>
      <value>yearly</value>
      <webElementGuid>225b8efb-5fb4-4ba2-adc8-b955a2f71132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annual</value>
      <webElementGuid>f3903529-3666-48f3-ba5e-d947ceebad44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;Pricing_wrapPricing__VuCjs&quot;]/div[@class=&quot;pricing_block_section&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;monthly_annual_select_toogle&quot;]/div[@class=&quot;box_select&quot;]/div[@class=&quot;btn_change_select_type btn_change_select_type_yearly&quot;]</value>
      <webElementGuid>4c9f7ca6-5c09-498d-a900-192cecf35b61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>fe89ecfb-59d1-4401-9a15-55b666aef788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly'])[1]/following::div[1]</value>
      <webElementGuid>7e23e7d5-c00a-4fb3-a432-18b75f2a53b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Easy to use, end-to-end platform for small teams to global enterprises'])[1]/following::div[6]</value>
      <webElementGuid>a87e68e5-ff0f-4f9b-8b06-5a5776cb5fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/preceding::div[2]</value>
      <webElementGuid>4e369a8a-511c-45e4-89c1-f8b4dce61457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Annual']/parent::*</value>
      <webElementGuid>c2741da5-90f2-4e49-9719-f3ad61ed5c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>7ea6784c-2257-41b9-ae8c-5d532184f2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Annual' or . = 'Annual')]</value>
      <webElementGuid>409d86c3-75a2-4fed-9170-95078a32683c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
