<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div4div4iframe1_c-ga7745lj71sz</name>
   <tag></tag>
   <elementGuidId>d0fd7cef-e62b-461e-bf68-438e19b15849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-ga7745lj71sz']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-ga7745lj71sz&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c59df1d5-6c28-4fed-af12-4a10966cc0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>58f49615-500f-4ab1-83f7-3e4a0a49f158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm</value>
      <webElementGuid>6e1a613d-0482-47d5-9a51-e289c6907d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-ga7745lj71sz</value>
      <webElementGuid>b0d87767-ccbb-4a5d-b6d9-a64d42c177c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a09e4a18-f74c-48cd-9e17-29b286432986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a97c5d18-9c25-4407-8a2d-9d4a5e6f9d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>7a16ba43-9c11-41b4-a387-8e0157d972a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]/div[4]/iframe[1]</value>
      <webElementGuid>f7b3bf0f-af9d-4f5a-8c2d-4aa76c675a50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-ga7745lj71sz']</value>
      <webElementGuid>7f9298c8-30e1-429e-9a49-de55106f6df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/iframe</value>
      <webElementGuid>a2d57f66-35fc-4d9f-963d-4e1fdfbec9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm' and @name = 'c-ga7745lj71sz']</value>
      <webElementGuid>42fe3a09-85df-48dc-90ef-c4d25829b84b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
