<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Do not allow space_a-ga7745lj71sz</name>
   <tag></tag>
   <elementGuidId>5d21bd0f-d37c-48ee-bbd7-30671bf6b5ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-ga7745lj71sz']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-ga7745lj71sz&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d93bab4e-bd18-4fa9-be96-7f0d4f7f1195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>07c47fa9-3682-4c90-b349-2ea011e489ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm&amp;co=aHR0cHM6Ly9xYS5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=rezicevpxe8k</value>
      <webElementGuid>2095c1ea-1d23-4a77-b199-5aed259dff3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>0b5d2f31-2171-469f-99f4-52cde3313c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>28f71170-930f-4720-9596-62d93d4854f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>de2bb429-777f-4ab0-b921-87cbdfa3d1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-ga7745lj71sz</value>
      <webElementGuid>c22143b2-5418-4563-8324-22f7d6c7b201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f6ad1271-e1ef-4c70-b6de-babcdf8cd21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e8679f6e-3d0a-469e-bc5d-fc431b0f8de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>c25d6b69-8bae-460f-b629-29be25d534e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;SignUp_wrapSignup__nLnnj&quot;]/div[@class=&quot;sign_up_section&quot;]/div[@class=&quot;sign_up_form&quot;]/form[@class=&quot;form_sign_up&quot;]/div[4]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>12a0b661-74b4-4249-98d4-8432013927a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-ga7745lj71sz']</value>
      <webElementGuid>19d08cf4-222d-4b24-a434-9b7de2ba3c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/div/form/div[4]/div/div/div/iframe</value>
      <webElementGuid>1534a3eb-1661-4152-8584-af5f1fcf1d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d8c96a59-1080-4f95-a3fd-09ff23972e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdN97weAAAAAIwrpaqkFdXBr_fBl9l3F0wXsWdm&amp;co=aHR0cHM6Ly9xYS5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=rezicevpxe8k' and @name = 'a-ga7745lj71sz']</value>
      <webElementGuid>e7d36ee9-7d8c-4fd6-9780-72278ef017cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
